### ISSUE TITLE
Feature Request: IPv6 support

### ISSUE THREAD

**Issue by rchac** [xdp-project/xdp-cpumap-tc#4]
Hey Jesper. Thank you again for this fantastic project. Requesting IPv6 support in xdp-cpumap-tc. I understand you're probably very busy so I understand you may not have time, and that it may take a while. If it is viable to implement though, it may helpful to many ISPs around the world. Thank you for your time, and for your work on this project and xdp overall. | Robert

**Comment by tohojo** [comment]
How about giving it a shot yourself and opening a pull request? :)

Should be pretty straight forward, you just need to implement the ipv6 header parsing. There's even some code in the bpf-examples repository you can reuse for this!

**Comment by rchac** [comment]
I was not sure where to find code examples for header parsing, that helps a lot. Thank you, Toke! I'll try my hand at it this weekend.

**Comment by dtaht** [comment]
If it was easy, someone else would have done it already.

**Comment by netoptimizer** [comment]
> If it was easy, someone else would have done it already.

Sorry @dtaht that is a fallacy.
If someone really needed this for production usage, then someone would have implemented it (or they would have hired someone to implement it, and contributed it back as this is GPL code). I will still claim that this is NOT difficult to implement.

All of the code @tohojo and I wrote in our [XDP-tutorial](https://github.com/xdp-project/xdp-tutorial) and [BPF-examples](https://github.com/xdp-project/bpf-examples/) contain IPv6 parsing code.

Let me be extra helpful and provide a direct link to the [parsing_helpers.h](https://github.com/xdp-project/bpf-examples/blob/master/include/xdp/parsing_helpers.h) header file.

**Comment by rchac** [comment]
I am very open to pay anyone willing to implement IPv6 parsing in xdp-cpumap-tc. The IPv6 parsing made sense to me, but once I tried integrating that with the existing bpf map in xdp-cpumap-tc I got lost. I don't have a CS background nor experience with C, so a lot of this goes over my head. Still, I'd like to help somehow, as IPv6 support would help smaller ISPs around the world. Perhaps I can compensate for the time spent to implement it?

Would anyone be interested in doing this as paid work? What is a fair feature bounty for this - I'm guessing around $1000 USD?

**Comment by tohojo** [comment]
Have a look at the `ipv6` branch for a starting point. It's a fairly naive conversion that still only supports single addresses for v6, and I've only compile-tested it so there are likely bugs. The conversion also uses IPv4-mapped v6-addresses to avoid duplicating maps, so everything looks like a v6 address in the output, and the debug output in particular is a bit hacky as far as this is concerned.

For full v6 support you'll probably want to match on prefixes rather than single IP addresses, but that requires a bit more surgery to the IP lookup mechanism (specifically, converting the map into an LPM map and fixing the lookups and inserts accordingly). For now, I'll leave that as an exercise to the next person who wants to pick this up... :)

**Comment by tohojo** [comment]
BTW, I consider the above a partial solution only, and if @rchac is serious about that (very generous!) $1k bounty offer, I'm happy for it to go to anyone who picks up what's in that branch and makes it actually usable in production :)

**Comment by rchac** [comment]
@tohojo Thank you very much for the work on the IPv6 branch! And yes I am serious about the $1000 USD bounty offer for an IPv6 parsing solution for xdp-cpumap-tc that can match traffic from/to matching IPv6 prefixes. Going to a commercial solution would cost more long term, so I'd rather contribute to an open source solution that everyone can use. We usually allocate a /56 IPv6 prefix to subscribers, so being able to match to anything on a sub's IPv6 prefix would be great.

**Comment by tohojo** [comment]
Cool! Happy to see someone with that attitude towards paying for open source work - much appreciated!

I'll ask around and see if I can get anyone to take you up on the offer :D

**Comment by dtaht** [comment]
I didn't know lpm had gone in years ago. ( https://www.coverfire.com/archives/2017/03/07/ebpf-longest-prefix-match-maps/ ). Obvious in retrospect.

**Comment by syadnom** [comment]
wondering if this has seen any attention in the last few months.  I arrived here through libreqos following rchac.

**Comment by syadnom** [comment]
@tohojo and @rchac you guys make any progress on this bounty work?  I'm willing to commit some funds as well.

**Comment by rchac** [comment]
@syadnom I can contribute $1500 toward IPv6 support for xdp-cpumap-tc. @netoptimizer and @tohojo - would either of you consider a $1500 code bounty to implement IPv6 support for xdp-cpumap-tc? I recognize that you're both quite busy with your careers, and want to make sure we are offering fair compensation for your time. 🙂 I suspect you two may be some of the only folks familiar enough with XDP and eBPF in this sphere to achieve this. I believe it would benefit many small ISPs in countries where IPv4 addresses are depleted.

**Comment by syadnom** [comment]
I can't spare that much but I'd put another $200 so you can buy beer and pizza during your coding efforts!

**Comment by dtaht** [comment]
The value of ipv6 support everywhere is now appreciating faster than bitcoin!

**Comment by syadnom** [comment]
> The value of ipv6 support everywhere is now appreciating faster than bitcoin!

Well I hope the skilled devs don't wait for the price to collapse before implementing lol

**Comment by tohojo** [comment]
Thank you all for the generous offers of funding! Unfortunately I'm personally not currently funding-constrained, but time-constrained. I do believe this is an important feature to have, though, so I'm planning to circle back to it eventually. However, I'll reiterate my comment above that if anyone else wants to take a crack at this, please go ahead and don't wait for me to get around to it! :)
